import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Nav from "../components/navbar/navbar";
import Footer from "../components/footer/footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-100`}>
        <div className="flex flex-col min-h-screen ">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
